##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    - aptitude
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - git
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libatk1.0-dev
    - libfribidi-dev
    - libxml2-dev
    - libxml2-utils
    - libglib2.0-dev
    - libglib2.0-doc
    - libgirepository1.0-dev
    - libpango1.0-doc
    - meson
    - xauth
    - xvfb

    #required for cdk-pixbuf
    - cmake
    - gi-docgen
    - librsvg2-dev
    - libtiff-dev
    - python3-docutils

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0 libctk-3-doc'
  - ./install-from-git https://github.com/cafe-desktop/cdk-pixbuf master meson '--libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu'

build_scripts:
  - ./before-build
  - ./make-scanbuild meson 'setup'
  - ./after-build

after_scripts:
  - ./gen-index -l 20
